<?php

namespace Database\Seeders;

use App\Models\SocialMediaReminder;
use App\Models\PostingCalendarReminder;
use App\Models\EmailCampaign;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MarketingMockSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // user_id: 1=Super Admin  2=vance  6=Anna  7=Media 1
        // contact ids: 1,2,6,8,9,10,12,16,19,20,22,24,29,31,33,42,47,51

        // ── SOCIAL MEDIA REMINDERS ────────────────────────────────────────────────
        $socialRows = [
            [
                'contact_id'              => 1,
                'company_name'            => 'The Linc KLCC',
                'package'                 => 'Premium',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'AM',
                'report_status'           => 'sent',
            ],
            [
                'contact_id'              => 6,
                'company_name'            => 'NAJI NYONYA CAFE',
                'package'                 => 'Basic',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'pending',
                'artwork_editing_status'  => 'in_progress',
                'posting_status'          => 'not_posted',
                'posting_staff_initials'  => 'VK',
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 9,
                'company_name'            => 'The Narra Filipino',
                'package'                 => 'Standard',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'AM',
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 10,
                'company_name'            => 'The Batik Boutique',
                'package'                 => 'Premium',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'VK',
                'report_status'           => 'sent',
            ],
            [
                'contact_id'              => 16,
                'company_name'            => 'Gula Cakery',
                'package'                 => 'Basic',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'pending',
                'artwork_editing_status'  => 'not_started',
                'posting_status'          => 'not_posted',
                'posting_staff_initials'  => null,
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 22,
                'company_name'            => 'KDK Fans Sdn Bhd',
                'package'                 => 'Standard',
                'month'                   => 'May 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'AM',
                'report_status'           => 'sent',
            ],
            [
                'contact_id'              => 29,
                'company_name'            => 'Mantra Indian Cuisine',
                'package'                 => 'Basic',
                'month'                   => 'May 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'VK',
                'report_status'           => 'sent',
            ],
            [
                'contact_id'              => 31,
                'company_name'            => 'Samba Brazilian Steakhouse',
                'package'                 => 'Premium',
                'month'                   => 'May 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'AM',
                'report_status'           => 'sent',
            ],
            [
                'contact_id'              => 33,
                'company_name'            => 'Avenue K Shopping Mall',
                'package'                 => 'Premium',
                'month'                   => 'July 2026',
                'content_calendar_status' => 'pending',
                'artwork_editing_status'  => 'not_started',
                'posting_status'          => 'not_posted',
                'posting_staff_initials'  => null,
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 47,
                'company_name'            => 'Boat Noodle',
                'package'                 => 'Standard',
                'month'                   => 'July 2026',
                'content_calendar_status' => 'pending',
                'artwork_editing_status'  => 'in_progress',
                'posting_status'          => 'not_posted',
                'posting_staff_initials'  => 'VK',
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 51,
                'company_name'            => 'Anna Hoo Clinic',
                'package'                 => 'Standard',
                'month'                   => 'July 2026',
                'content_calendar_status' => 'pending',
                'artwork_editing_status'  => 'not_started',
                'posting_status'          => 'not_posted',
                'posting_staff_initials'  => null,
                'report_status'           => 'pending',
            ],
            [
                'contact_id'              => 42,
                'company_name'            => 'Lalaport Bukit Bintang',
                'package'                 => 'Premium',
                'month'                   => 'June 2026',
                'content_calendar_status' => 'approved',
                'artwork_editing_status'  => 'done',
                'posting_status'          => 'posted',
                'posting_staff_initials'  => 'AM',
                'report_status'           => 'pending',
            ],
        ];

        foreach ($socialRows as $row) {
            SocialMediaReminder::updateOrCreate(
                ['contact_id' => $row['contact_id'], 'month' => $row['month']],
                $row
            );
        }

        // ── POSTING CALENDAR REMINDERS ────────────────────────────────────────────
        $platforms = ['Instagram', 'Facebook', 'TikTok', 'LinkedIn', 'Twitter/X'];

        $calendarRows = [
            [
                'user_id'  => 7,
                'title'    => 'The Linc KLCC — June promotion reel',
                'platform' => 'Instagram',
                'client'   => 'The Linc KLCC',
                'date'     => $now->copy()->subDays(3)->toDateString(),
                'time'     => '10:00',
                'status'   => 'posted',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Gula Cakery — new menu carousel',
                'platform' => 'Facebook',
                'client'   => 'Gula Cakery',
                'date'     => $now->copy()->subDays(2)->toDateString(),
                'time'     => '12:00',
                'status'   => 'posted',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Boat Noodle — weekday promo story',
                'platform' => 'Instagram',
                'client'   => 'Boat Noodle',
                'date'     => $now->copy()->subDay()->toDateString(),
                'time'     => '11:00',
                'status'   => 'posted',
            ],
            [
                'user_id'  => 7,
                'title'    => 'KDK Fans — product highlight video',
                'platform' => 'TikTok',
                'client'   => 'KDK Fans Sdn Bhd',
                'date'     => $now->toDateString(),
                'time'     => '09:00',
                'status'   => 'scheduled',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Samba Steakhouse — weekend special',
                'platform' => 'Instagram',
                'client'   => 'Samba Brazilian Steakhouse',
                'date'     => $now->toDateString(),
                'time'     => '18:00',
                'status'   => 'scheduled',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Avenue K — July events lineup',
                'platform' => 'Facebook',
                'client'   => 'Avenue K Shopping Mall',
                'date'     => $now->copy()->addDays(1)->toDateString(),
                'time'     => '10:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Anna Hoo Clinic — skincare tips reel',
                'platform' => 'Instagram',
                'client'   => 'Anna Hoo Clinic',
                'date'     => $now->copy()->addDays(2)->toDateString(),
                'time'     => '09:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Lalaport BB — mid-year sale post',
                'platform' => 'Facebook',
                'client'   => 'Lalaport Bukit Bintang',
                'date'     => $now->copy()->addDays(2)->toDateString(),
                'time'     => '12:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Narra Filipino — Rizal Day feature',
                'platform' => 'Instagram',
                'client'   => 'The Narra Filipino',
                'date'     => $now->copy()->addDays(3)->toDateString(),
                'time'     => '11:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Mantra Indian Cuisine — lunch deal',
                'platform' => 'TikTok',
                'client'   => 'Mantra Indian Cuisine',
                'date'     => $now->copy()->addDays(4)->toDateString(),
                'time'     => '13:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Batik Boutique — heritage collection',
                'platform' => 'LinkedIn',
                'client'   => 'The Batik Boutique',
                'date'     => $now->copy()->addDays(5)->toDateString(),
                'time'     => '10:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'NAJI Nyonya Cafe — weekend brunch',
                'platform' => 'Instagram',
                'client'   => 'NAJI NYONYA CAFE',
                'date'     => $now->copy()->addDays(5)->toDateString(),
                'time'     => '09:30',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 2,
                'title'    => 'Boat Noodle — testimonial repost',
                'platform' => 'Twitter/X',
                'client'   => 'Boat Noodle',
                'date'     => $now->copy()->addDays(6)->toDateString(),
                'time'     => '14:00',
                'status'   => 'pending',
            ],
            [
                'user_id'  => 7,
                'title'    => 'Avenue K — July F&B event teaser',
                'platform' => 'Instagram',
                'client'   => 'Avenue K Shopping Mall',
                'date'     => $now->copy()->addDays(7)->toDateString(),
                'time'     => '10:00',
                'status'   => 'pending',
            ],
        ];

        foreach ($calendarRows as $row) {
            PostingCalendarReminder::create($row);
        }

        // ── EMAIL CAMPAIGNS ───────────────────────────────────────────────────────
        $campaigns = [
            [
                'name'               => 'June 2026 Newsletter',
                'subject'            => 'Your June Highlights from Bluedale',
                'preview_text'       => 'Exclusive updates, promotions & events — just for you.',
                'body'               => '<p>Dear Valued Client,</p><p>Here are the highlights from our network this June...</p>',
                'sender_name'        => 'Bluedale Marketing',
                'sender_email'       => 'marketing@bluedale.com.my',
                'status'             => 'sent',
                'scheduled_at'       => $now->copy()->subDays(10)->toDateTimeString(),
                'sent_at'            => $now->copy()->subDays(10)->toDateTimeString(),
                'audience_count'     => 420,
                'sent_count'         => 418,
                'delivered_count'    => 410,
                'opened_count'       => 187,
                'clicked_count'      => 52,
                'bounced_count'      => 8,
                'unsubscribed_count' => 2,
                'open_rate'          => 45.6,
                'click_rate'         => 12.7,
                'user_id'            => 1,
            ],
            [
                'name'               => 'Ramadan Promo Blast',
                'subject'            => 'Celebrate Ramadan with Our Special Packages',
                'preview_text'       => 'Limited-time offers for the holy month.',
                'body'               => '<p>Assalamualaikum,</p><p>We have curated special Ramadan promotions for you...</p>',
                'sender_name'        => 'Bluedale Marketing',
                'sender_email'       => 'marketing@bluedale.com.my',
                'status'             => 'sent',
                'scheduled_at'       => $now->copy()->subDays(60)->toDateTimeString(),
                'sent_at'            => $now->copy()->subDays(60)->toDateTimeString(),
                'audience_count'     => 390,
                'sent_count'         => 388,
                'delivered_count'    => 381,
                'opened_count'       => 210,
                'clicked_count'      => 78,
                'bounced_count'      => 7,
                'unsubscribed_count' => 1,
                'open_rate'          => 55.1,
                'click_rate'         => 20.5,
                'user_id'            => 1,
            ],
            [
                'name'               => 'Q2 Social Media Package Renewal',
                'subject'            => 'Time to Renew Your Social Media Package',
                'preview_text'       => 'Upgrade & save — your Q3 options inside.',
                'body'               => '<p>Hi there,</p><p>Your current social media package is coming up for renewal...</p>',
                'sender_name'        => 'Bluedale Accounts',
                'sender_email'       => 'accounts@bluedale.com.my',
                'status'             => 'sent',
                'scheduled_at'       => $now->copy()->subDays(25)->toDateTimeString(),
                'sent_at'            => $now->copy()->subDays(25)->toDateTimeString(),
                'audience_count'     => 85,
                'sent_count'         => 85,
                'delivered_count'    => 83,
                'opened_count'       => 49,
                'clicked_count'      => 21,
                'bounced_count'      => 2,
                'unsubscribed_count' => 0,
                'open_rate'          => 59.0,
                'click_rate'         => 25.3,
                'user_id'            => 2,
            ],
            [
                'name'               => 'July 2026 Merdeka Campaign Preview',
                'subject'            => 'Get Ready for Merdeka — Book Your Campaign Slot',
                'preview_text'       => 'Secure your spot before slots fill up.',
                'body'               => '<p>Dear Valued Partner,</p><p>Malaysia Day is around the corner — let us help you make an impact...</p>',
                'sender_name'        => 'Bluedale Marketing',
                'sender_email'       => 'marketing@bluedale.com.my',
                'status'             => 'scheduled',
                'scheduled_at'       => $now->copy()->addDays(7)->toDateTimeString(),
                'sent_at'            => null,
                'audience_count'     => 450,
                'sent_count'         => 0,
                'delivered_count'    => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'bounced_count'      => 0,
                'unsubscribed_count' => 0,
                'open_rate'          => 0,
                'click_rate'         => 0,
                'user_id'            => 1,
            ],
            [
                'name'               => 'New Client Welcome Email',
                'subject'            => 'Welcome to Bluedale — Here is What Happens Next',
                'preview_text'       => 'We are excited to have you on board.',
                'body'               => '<p>Welcome!</p><p>Thank you for choosing Bluedale as your marketing partner...</p>',
                'sender_name'        => 'Bluedale Team',
                'sender_email'       => 'hello@bluedale.com.my',
                'status'             => 'draft',
                'scheduled_at'       => null,
                'sent_at'            => null,
                'audience_count'     => 0,
                'sent_count'         => 0,
                'delivered_count'    => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'bounced_count'      => 0,
                'unsubscribed_count' => 0,
                'open_rate'          => 0,
                'click_rate'         => 0,
                'user_id'            => 2,
            ],
            [
                'name'               => 'F&B Industry Spotlight — June',
                'subject'            => 'See How Top KL Restaurants Are Winning on Social Media',
                'preview_text'       => 'Case studies & proven tactics inside.',
                'body'               => '<p>Hi,</p><p>This month we spotlight F&B clients who saw exceptional social media growth...</p>',
                'sender_name'        => 'Bluedale Insights',
                'sender_email'       => 'insights@bluedale.com.my',
                'status'             => 'draft',
                'scheduled_at'       => null,
                'sent_at'            => null,
                'audience_count'     => 0,
                'sent_count'         => 0,
                'delivered_count'    => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'bounced_count'      => 0,
                'unsubscribed_count' => 0,
                'open_rate'          => 0,
                'click_rate'         => 0,
                'user_id'            => 1,
            ],
        ];

        foreach ($campaigns as $campaign) {
            EmailCampaign::create($campaign);
        }
    }
}
